#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('BASE_PATH') or define('BASE_PATH', __DIR__ . '/app/Modules/Console');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/app/config/bootstrap.php';

defined('PROJECT_ID') or define('PROJECT_ID', \App\App::PROJECT_ID_TRAD3R);

$config = \App\App::i()->buildConfig(\App\App::CONFIG_MODULE_CONSOLE);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
